#! /bin/sh
 # /etc/init.d/customstartup
 # Required-Start: $all
 
 case "$1" in
   start)
     # /usr/local/bin/ts7500ctl --redledon #LED is used in web script as indicator
     ## If you are launching a daemon or other long running processes
     ## this should be started with
     # nohup /usr/local/bin/yourdaemon &
	 # Phone-Detector Start
	 #echo "Starting Phone-Detector."
	 #nohup python /home/homeautomation/phone_ping.py >/home/ping.txt 2>&1 &
	 # Direct Control Startup
	 echo "Starting DIO Input Control."
	 nohup python /home/homeautomation/direct_input.py >/home/DIO.txt 2>&1 &
     # Web-Server Start
     echo "Starting Home Automation Web Server..."
     #python /home/homeautomation/manage.py runserver 192.168.1.15:80
     python /home/homeautomation/webapp.py
     echo "(!) Server Closed!"
     ;;
   stop)
     /usr/local/bin/ts7500ctl --redledoff
     ;;
   *)
     echo "Usage: customstartup start|stop" >&2
     exit 3
     ;;
 esac
 
 exit 0
