
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# HTTP Configuration
http:
  server_port: 80

# On Air Sign
light:
  - platform: mqtt
    name: wled_onair
    unique_id: wled_onair
    state_topic: "wled/onair/g"
    command_topic: "wled/onair/api"
    rgb_state_topic: "wled/onair/c"
    rgb_command_topic: "wled/onair/col"
    brightness_command_topic: "wled/onair"
    brightness_state_topic: "wled/onair/g"
    brightness_value_template: "{{value }} "
    rgb_command_template: "{{ '#%02x%02x%02x' | format(red, green, blue)}}"
    rgb_value_template: "{{ value[1:3] | int(base=16) }},{{ value[3:5] | int(base=16) }},{{ value[5:7]| int(base=16) }}"
    qos: 0
    optimistic: true
    on_command_type: "first"
    payload_on: "T=1"
    payload_off: "T=0"
    effect_list:
      - "[FX=00]  STATIC"
      - "[FX=01]  BLINK"
      - "[FX=02]  BREATH"
      - "[FX=03]  COLOR_WIPE"
      - "[FX=04]  COLOR_WIPE_RANDOM"
      - "[FX=05]  RANDOM_COLOR"
      - "[FX=06]  COLOR_SWEEP"
      - "[FX=07]  DYNAMIC"
      - "[FX=08]  RAINBOW"
      - "[FX=09]  RAINBOW_CYCLE"
      - "[FX=10]  SCAN"
      - "[FX=11]  DUAL_SCAN"
      - "[FX=12]  FADE"
      - "[FX=13]  THEATER_CHASE"
      - "[FX=14]  THEATER_C_RAINBOW"
      - "[FX=15]  RUNNING_LIGHTS"
      - "[FX=16]  SAW"
      - "[FX=17]  TWINKLE"
      - "[FX=18]  DISSOLVE"
      - "[FX=19]  DISSOLVE_RANDOM"
      - "[FX=20]  SPARKLE"
      - "[FX=21]  FLASH_SPARKLE"
      - "[FX=22]  HYPER_SPARKLE"
      - "[FX=23]  STROBE"
      - "[FX=24]  STROBE_RAINBOW"
      - "[FX=25]  MULTI_STROBE"
      - "[FX=26]  BLINK_RAINBOW"
      - "[FX=27]  ANDROID"
      - "[FX=28]  CHASE_COLOR"
      - "[FX=29]  CHASE_RANDOM"
      - "[FX=30]  CHASE_RAINBOW"
      - "[FX=31]  CHASE_FLASH"
      - "[FX=32]  CHASE_FLASH_RANDOM"
      - "[FX=33]  CHASE_RAINBOW_WHITE"
      - "[FX=34]  COLORFUL"
      - "[FX=35]  TRAFFIC_LIGHT"
      - "[FX=36]  COLOR_SWEEP_RANDOM"
      - "[FX=37]  RUNNING_COLOR"
      - "[FX=38]  RUNNING_RED_BLUE"
      - "[FX=39]  RUNNING_RANDOM"
      - "[FX=40]  LARSON_SCANNER"
      - "[FX=41]  COMET"
      - "[FX=42]  FIREWORKS"
      - "[FX=43]  RAIN"
      - "[FX=44]  MERRY_CHRISTMAS"
      - "[FX=45]  FIRE_FLICKER"
      - "[FX=46]  GRADIENT"
      - "[FX=47]  LOADING"
      - "[FX=48]  DUAL_COLOR_WIPE_IN_OUT"
      - "[FX=49]  DUAL_COLOR_WIPE_IN_IN"
      - "[FX=50]  DUAL_COLOR_WIPE_OUT_OUT"
      - "[FX=51]  DUAL_COLOR_WIPE_OUT_IN"
      - "[FX=52]  CIRCUS_COMBUSTUS"
      - "[FX=53]  HALLOWEEN"
      - "[FX=54]  TRICOLOR_CHASE"
      - "[FX=55]  TRICOLOR_WIPE"
      - "[FX=56]  TRICOLOR_FADE"
      - "[FX=57]  LIGHTNING"
      - "[FX=58]  ICU"
      - "[FX=59]  MULTI_COMET"
      - "[FX=60]  DUAL_LARSON_SCANNER"
      - "[FX=61]  RANDOM_CHASE"
      - "[FX=62]  OSCILLATE"
      - "[FX=63]  PRIDE_2015"
      - "[FX=64]  JUGGLE"
      - "[FX=65]  PALETTE"
      - "[FX=66]  FIRE_2012"
      - "[FX=67]  COLORWAVES"
      - "[FX=68]  BPM"
      - "[FX=69]  FILLNOISE8"
      - "[FX=70]  NOISE16_1"
      - "[FX=71]  NOISE16_2"
      - "[FX=72]  NOISE16_3"
      - "[FX=73]  NOISE16_4"
      - "[FX=74]  COLORTWINKLE"
      - "[FX=75]  LAKE"
      - "[FX=76]  METEOR"
      - "[FX=77]  METEOR_SMOOTH"
      - "[FX=78]  RAILWAY"
      - "[FX=79]  RIPPLE"
    effect_command_topic: "wled/onair/api"
    effect_state_topic: "wled/onair/api"
    effect_value_template: "{{ value }}"

# Switches
switch:
  - name: Living_Room_Scentsy
    unique_id: livingscent
    platform: mqtt
    state_topic: stat/living_scent/POWER
    command_topic: cmnd/living_scent/POWER
    availability_topic: tele/living_scent/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
  - name: Study_Caboose_Lamp
    unique_id: cabooselamp
    platform: mqtt
    state_topic: stat/study_cab/POWER
    command_topic: cmnd/study_cab/POWER
    availability_topic: tele/study_cab/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
  - name: Train_Display
    unique_id: traindisplay
    platform: mqtt
    state_topic: stat/train_disp/POWER
    command_topic: cmnd/train_disp/POWER
    availability_topic: tele/train_disp/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
  - name: Living_Room_Bookshelf
    unique_id: livingbookshelf
    platform: mqtt
    state_topic: stat/liv_books/POWER
    command_topic: cmnd/liv_books/POWER
    availability_topic: tele/liv_books/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
  - name: Outdoor Holiday Lights
    unique_id: holidayoutdoorlights
    platform: mqtt
    state_topic: stat/holidayoutdoor/POWER
    command_topic: cmnd/holidayoutdoor/POWER
    availability_topic: tele/holidayoutdoor/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
  - name: Back Porch Light
    unique_id: backporchlight
    platform: mqtt
    state_topic: stat/backporch/POWER
    command_topic: cmnd/backporch/POWER
    availability_topic: tele/backporch/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
  - name: Study Floor Lamp
    unique_id: studyfloorlamp
    platform: mqtt
    state_topic: stat/study_floor/POWER
    command_topic: cmnd/study_floor/POWER
    availability_topic: tele/study_floor/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
